@Api_HostAddress = https://localhost:7222

GET {{Api_HostAddress}}/Translate?SourceLanguage=pt-BR&TargetLanguage=en-US&Text=Verifique%20se%20o%20paciente%20est%C3%A1%20posicionado%20da%20maneira%20correta
Accept: text/plain

###